version: '3.8'

services:
  postgres:
    image: postgis/postgis:15-3.3
    container_name: red-atlas-postgres
    environment:
      POSTGRES_DB: red_atlas_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5439:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: red-atlas-redis
    ports:
      - "6381:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes --maxmemory 256mb --maxmemory-policy allkeys-lru
    restart: unless-stopped

volumes:
  postgres_data:
  redis_data: