version: '3.8'

services:
  postgres:
    image: postgis/postgis:15-3.3
    container_name: red-atlas-postgres
    environment:
      POSTGRES_DB: red_atlas_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5439:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data: